---
abstract: 'We are CPAN Authors of AnyEvent!'
author:
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  lib::abs: 0.90
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-AnyEvent
no_index:
  directory:
    - example
    - inc
    - t
requires:
  Acme::CPANAuthors: 0
  Acme::CPANAuthors::Register: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
